### ISSUE TITLE
Installation error 0x80070005: access is denied

### ISSUE THREAD

**Issue by nalhiff** [ArvinZJC/PaimonTray#6]
do you have any plan to make it into portable program? since mine has a faulty if its program based on microsoft store alike

![image](https://user-images.githubusercontent.com/36839431/176682360-cb11ae77-4146-46c2-9cc5-a53fc7766480.png)

**Comment by ArvinZJC** [comment]
I cannot reproduce this error on my device (Win11 21H2) and my virtual environment (Win10 21H2). I would suggest as follows:
1. Currently, sorry but no plan for a portable program. May consider this feature in the future.
2. I notice that this may be [an App Installer bug on Win10 20H1](https://techcommunity.microsoft.com/t5/msix/windows-10-2004-msix-not-updating-please-check-whether-the/m-p/1466701). So could you please tell me your Windows version?
3. Have you tried the way to install the app via the command line stated in [the Q&A section](https://github.com/ArvinZJC/PaimonTray#-why-not-give-it-a-try)? If the problem still exists, I may try reproducing the issue from my end.
4. Otherwise, I would appreciate your patience with the Microsoft Store channel release if you can use Microsoft Store.

**Comment by nalhiff** [comment]
hello!
thanks for the reply, really appreciate your comment.

1. dont worry about it, i just wondering if u do some future plan
2. my winver is win10 21H2 (19044.1766)
![image](https://user-images.githubusercontent.com/36839431/176725087-e78f2dc5-3874-47ed-a165-45090824b1f5.png)
3. it is, i already tried and they gave me the same code
![image](https://user-images.githubusercontent.com/36839431/176726396-83f6a35a-567b-4068-b907-093b1af6d503.png)
4. i will try and gave some feedback

once again, thanks for your reply

**Comment by ArvinZJC** [comment]
I have updated the released `.msixbundle` file for manual installation because I forgot to sign with the timestamp.

Yet this should not be the root cause of this issue. You may try using the latest `.msixbundle` file to install the app at an _**elevated**_ PowerShell prompt (you may need to install the app as an admin due to the "access is denied" error). I'm not sure if this can solve the issue, but I reckon the issue does not relate to the package installer provided in the releases because none of the 5 machines/virtual env tested reported this error. It's an MSIX-specific installation problem in several cases that needs Microsoft to provide a more detailed explanation.
